### ISSUE TITLE
Clarification re: Python 2 and affiliated packages

### ISSUE THREAD

**Issue by jakevdp** [astropy/astropy.github.com#102]
The [affiliated package info](http://www.astropy.org/affiliated/#affiliated-instructions) specifically mentions Python 3.x compatibility, but not Python 2.x. Is Python 2.x optional, or merely implied? I think it would be helpful to clarify that section. Personally, I would be in favor of pointing to tools like six and python-future and recommending single-codebase Python 2&3 support.

**Comment by pllim** [comment]
Astropy is dropping Python 2, so we can close this?

**Comment by bsipocz** [comment]
Actually I think we should change this with the upcoming python3 only core package. Mention only the python2 compatibility in the table, and require python3 as default?

**Comment by astrofrog** [comment]
Sorry for dropping the ball on this. I believe it's no longer important to indicate if packages are Python 2-compatible in our overview page. In addition the affiliated package guidelines mention that not supporting Python 3 will become unacceptable on 1 Jan 2020 (see https://github.com/astropy/astropy-procedures/pull/132 for a clarification).
