### ISSUE TITLE
Place the NumFOCUS digital stamp on astropy home page

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy.github.com#105]
From the NumFOCUS communications director:

We'd really like to make sure that our relationship to sponsored projects is clearly delineated on each project's individual website. To that end, we're requesting all sponsored projects to take the following steps:

Please post the NumFOCUS [digital stamp](https://drive.google.com/open?id=0BwwsN83Hnz4XSDFzX1h5M0M1QVk) on the homepage of your website (at the bottom or in the footer is fine).

Link the image to this url: www.numfocus.org

**Comment by kelle** [comment]
This should be high priority.

**Comment by bsipocz** [comment]
it's currently at the bottom of "about": http://www.astropy.org/about.html

**Comment by kelle** [comment]
I think we should consider adding a footer so that this is on every page.

**Comment by apooravc** [comment]
@kelle @granttremblay Should I work on adding a footer to every page which would contain the code-of-conduct text & the NumFOCUS stamp or just add the stamp (as it is on "about" page) to homepage?

**Comment by astrofrog** [comment]
@apooravc - the code of conduct full text is definitely too long, but if you can find a way to make a footer with the NumFOCUS stamp and a link to the astropy code of conduct that would be great!
