### ISSUE TITLE
Deprecate tutorials.astropy.org?

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy.github.com#107]
Now that the tutorials are in the main Astropy docs, we should probably remove the page currently at tutorials.astropy.org and redirect instead to the main docs?

cc @eteq @kelle @adrn

**Comment by kelle** [comment]
Are you referring to the gallery? I may have missed something and/or not fully understand what you mean by the "tutorials are in the main Astropy docs". If you are referring the gallery, it was not my understanding that we intended the gallery to replace the tutorials but rather supplement them.

**Comment by astrofrog** [comment]
@kelle - yes, sorry, I realized that after - will close this for now!
