### ISSUE TITLE
Make roles footnotes in-page hyperlinks

### ISSUE THREAD

**Issue by eteq** [astropy/astropy.github.com#114]
We merged #111 from @taldcroft adding all the roles to http://www.astropy.org/team.html . One quirk there: the footnotes don't seem to be live links.  Were they supposed to be, @taldcroft?

**Comment by astrofrog** [comment]
It might also be nice to make just the footnote number blue once this works, not the name?

**Comment by taldcroft** [comment]
The intent of the all-blue entry was to make it stand out a bit.  But if that is too much then it is easy enough to remove the colors entirely.  Having only the footnote in blue would not be of much value since for a tiny number there is visually very little difference between blue and black.

**Comment by taldcroft** [comment]
About the original issue, I did not intend to make the footnotes live links.  I figured the table is short enough and people should generally be aware of the way footnotes worked for the first ~thousand years of writing before HTML.  :smile:

**Comment by eteq** [comment]
Hah, ok, fair enough.  I think the blue made me think link, but this is fine, so I'll just close this.
