### ISSUE TITLE
Add David Shupe to TBD role(s)

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy.github.com#127]
> Dear Astropy Coordinators
> 
> I have a longstanding interest in WCS and astropy.wcs and I use astropy.io.fits very extensively. Those would be big sub-packages to take on though. astropy.constants would be easier.
> 
> One caveat is that although I’ve been listed as a contributor to Astropy for a long time, I haven’t successfully contributed code yet. However, my current roles at IPAC are now half-time doing Python development for the ZTF project, and half-time working on LSST Science User Interface and Tools where I am responsible for integrating visualization tools into the LSST stack. I’m learning the LSST stack development workflow which will help in improving my skill level for Astropy contributions and I have made my first successful contribution to the stack. (I am also a big proponent of bringing more Astropy into LSST!)
> 
> Regards,
> David
> 
> David Shupe, Ph.D.
> Staff Scientist, ZTF and LSST
> IPAC/Caltech

**Comment by eteq** [comment]
we're going to deputy him for constants and then maybe `wcs` once we figure out the lead situation

**Comment by eteq** [comment]
@taldcroft will e-mail re:constants, and @eteq re: wcs

**Comment by eteq** [comment]
@taldcroft - can you confirm whether you've contacted David about this?  I was going to wait on your initial email before contacting him re: wcs

**Comment by taldcroft** [comment]
@eteq - just sent email.

**Comment by pllim** [comment]
Added him to `constants`, so we can close this?

**Comment by stargaser** [comment]
It can be closed as far as I am concerned.
