### ISSUE TITLE
Rename repository to astropy.org?

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy.github.com#134]
We should either change the repo name to astropy.github.io or astropy.org - any objections? (I prefer the latter)

**Comment by eteq** [comment]
@astrofrog - doesn't that break everything?  I think the repository name has to be ``<something>.github.com`` to for with Github pages?

**Comment by eteq** [comment]
(because otherwise the URL is ``astropy.github.io/astropy.org`` or something like that

**Comment by eteq** [comment]
I'm getting this from the first two steps of https://pages.github.com/

**Comment by astrofrog** [comment]
@eteq - ah of course, sorry - wasn't thinking straight. Still worth changing to ``.io`` instead of ``.com``?

**Comment by taldcroft** [comment]
I am Ok with changing to `.io`.

**Comment by eteq** [comment]
I'm OK in principal with changing it to ``.io``, but I'm worried there might be side-effects?  We'll have to update the DNS but that's fairly transient... but are there search engine problems or links to this repo in documentation floating around that we might forget to update?

(Maybe not - I'm genuinely asking, but it never occurred to me that this repo might change names so I may be guilty of embedding it in some hard-to-change place...)

**Comment by taldcroft** [comment]
I thought that github automatically does the redirect.  I can type `astropy.github.io` and `astropy.github.com` and they both redirect to `astropy.org` (as shown in the browser URL window).  Likewise `python4astronomers.github.com` redirects to `.io`.

But maybe I'm missing some pesky details.

**Comment by eteq** [comment]
Ah, I didn't realize that - that fixes the DNS concern, but for the documentation I'm more concerned about the link to the *repo*: https://github.com/astropy/astropy.github.com.  For example, there's a link on http://www.astropy.org/affiliated/ that points there which will break if we rename it.  Obviously we can fix that one but I'm worried that there are others more deeply buried (forum posts, astropy-dev, etc).  

But maybe we can make https://github.com/astropy/astropy.github.com redirect to https://github.com/astropy/astropy.github.io ?  If so, all my concerns are eliminated...

**Comment by astrofrog** [comment]
Normally GitHub auto-redirects when repositories are renamed. But to be honest I don't feel strongly about this, and we could just close this. I'm easy going :)

**Comment by eteq** [comment]
To be clear, I do think this is a good idea on balance, I'm just afraid it will break something...

**Comment by taldcroft** [comment]
At the end I would vote to just close this.  Benefit vs. risk doesn't seem high enough.
