### ISSUE TITLE
Add link to http://astropy.userecho.com on website

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy.github.com#142]
As discussed in https://github.com/astropy/astropy/issues/4673 and https://github.com/astropy/astropy/issues/1457 we should add a link to http://astropy.userecho.com to the website.

**Comment by granttremblay** [comment]
Here's a quick draft of a simple link added to the Contribute section. Do we want something more prominent than this? 
<img width="982" alt="screen shot 2017-01-03 at 3 00 27 pm" src="https://cloud.githubusercontent.com/assets/2238418/21622906/7e1f461a-d1c5-11e6-993f-aa1b22102185.png">

**Comment by kelle** [comment]
This looks good to me.

**Comment by granttremblay** [comment]
Looks like we're no longer using UserEcho? 

http://astropy.userecho.com/

**Comment by bsipocz** [comment]
I hasn't really picked up, but I cannot recall that we officially abandoned it.

**Comment by granttremblay** [comment]
Whoops! Nevermind - when I clicked the link a minute ago, it was 404ing for me. Works now. 

I'll add the link to the site as above.
