### ISSUE TITLE
Revive labcoat with Astropy logo

### ISSUE THREAD

**Issue by pllim** [astropy/astropy.github.com#158]
http://astropy.logosoftwear.com/ does not have a labcoat selection anymore.

Moved over from astropy/astropy#5524 as @bsipocz suggested. @perrygreenfield will look into it.

**Comment by eteq** [comment]
😱  we must have our lab coat!

**Comment by perrygreenfield** [comment]
OK, OK, I've added a labcoat product :-) I don't have my labcoat handy so I'm not 100% sure I've done it the same way. Please check and let me know if is acceptable.

**Comment by pllim** [comment]
@perrygreenfield , logo on the wrong side. Here is a photo of my labcoat:
![img_20170629_120345](https://user-images.githubusercontent.com/2090236/27699204-851e1742-5cc7-11e7-8b04-22f999acd0a8.jpg)

**Comment by perrygreenfield** [comment]
As it turns out I just checked it before seeing the previous comment and revised it to be on the right side. Though the template designer didn't let me make it quite as big as I measured on mine (perhaps a half inch shorter if the designer shows it accurately)

**Comment by pllim** [comment]
I can see the labcoat on the listing now, and with logo on the correct side. Thanks!
