### ISSUE TITLE
Add a list of organizations that have supported astropy

### ISSUE THREAD

**Issue by eteq** [astropy/astropy.github.com#166]
Prompted by the discussion in astropy/astropy#6299, I figured I should start a discussion here: should we have a place where we have logos of organizations that have in some way directly supported astropy development?  Some obvious inclusions would be STScI and CfA/CXC... Perhaps also LSST (depending on how @parejkoj intereprets some of his contributions).  I imagine there are others that I am less familiar with, too.

**Comment by eteq** [comment]
I should say that I *thought* there was already an issue about this, but couldn't find it.  But if anyone else sees it, feel free to close this as a duplicate...

**Comment by taldcroft** [comment]
I only remember previous discussion about orgs that *use* astropy.

We probably want to say "directly or indirectly supported" to be clear that this may include institutional support of staff who are working on astropy in their discretionary time.

We might optionally allow for associating contributor names with the institutions.  This would probably give a vague indication of support level, and also give some traceability for people who randomly find this page and wonder "who at the CXC is working on Astropy?"  But of course it would be opt-in.

**Comment by parejkoj** [comment]
I would certainly consider my contributions (handful of bugfixes, porting some LSST code) to be "support" of astropy by LSST. I can check further up the chain if any disagrees, but I'd be rather surprised if that were the case.

**Comment by granttremblay** [comment]
This is a nice idea, and I'm happy to help implement it. The badges would nicely fit alongside #117.

**Comment by bsipocz** [comment]
There is also google ;)

**Comment by eteq** [comment]
Ah, good point @bsipocz - we probably want to say GSoC (they have that nice logo at https://developers.google.com/open-source/gsoc/), strictly speaking, to not imply it's actual Google employees or something.

**Comment by bsipocz** [comment]
Oh, sure. You got what I meant.

**Comment by pllim** [comment]
If you want a badge, I made one for STScI using sanctioned color scheme:
```rst
.. image:: https://img.shields.io/badge/powered%20by-STScI-blue.svg?colorA=707170&colorB=3e8ddd&style=flat
    :target: http://www.stsci.edu
    :alt: Powered by STScI Badge
```

Or you can just use the official STScI logo (several variants are available).

**Comment by pllim** [comment]
Listed now at the bottom of https://www.astropy.org/credits.html
