### ISSUE TITLE
add donate button

### ISSUE THREAD

**Issue by kelle** [astropy/astropy.github.com#168]
dedicated donate button for astropy via numfocus. 

I sent an email to numfocus to help get this moving.

**Comment by astrofrog** [comment]
See https://github.com/astropy/astropy/pull/6380 for the link to use

**Comment by apooravc** [comment]
@astrofrog May I take this one up?

**Comment by apooravc** [comment]
@kelle Working on it.

**Comment by eteq** [comment]
@apooravc - revisiting this after a break... I think actually it makes sense to be in *both* - the astropy repo is for just the core package, and these donations go to the Astropy Project as a whole (which includes affiliated pakcages)
