### ISSUE TITLE
Remove old versions of astropy from drop-down menu

### ISSUE THREAD

**Issue by pllim** [astropy/astropy.github.com#186]
Remove old versions of astropy from drop-down menu under "Documentation" at the top nav bar at http://www.astropy.org/ .

**Comment by apooravc** [comment]
@pllim If it's still needed, up to which version (from v0.1)?

**Comment by pllim** [comment]
Unfortunately, that is not my call. A decision might be needed from @astropy/coordinators .

**Comment by apooravc** [comment]
@pllim The issue #201 argues adding the astropy coordinated packages in place of older versions of the core package, with the core package at top in the drop-down list. Could you have a look?

**Comment by pllim** [comment]
Again, that is not my decision to made. I simply opened this issue as a follow-up of some discussions but I don't manage the site.

**Comment by bsipocz** [comment]
@apooravc - #201 will definitely need to be part of a bigger documentation and webpage overhaul, while this issue as @pllim  mentioned above needs a decision first.
