### ISSUE TITLE
Better unify all packages under the astropy project

### ISSUE THREAD

**Issue by pllim** [astropy/astropy.github.com#187]
As discussed during NY coordination meeting.

"What should external non-astropy people expect when they visit astropy doc (e.g., expectations for numpy and scipy are clear)? "

"Add graphical representation of the different relationships."

**Comment by bsipocz** [comment]
Re the title: over at sunpy they did something similar with a gsoc project this year. Basically it's seamless for the user whether they're reading the core, or the affiliated documentation. And more importantly the headline menu stays, so it's really easy to browse around without the need hit the "back" in the browser.

**Comment by kelle** [comment]
Kelle sending email to @caldair to schedule a meeting.

**Comment by eteq** [comment]
I'm closing this in favor of #190 because that's I think what we settled on for the new separation-of-concerns
