### ISSUE TITLE
Update web site to reflect "Astropy Coordinated" and "Astropy Affiliated" package language

### ISSUE THREAD

**Issue by eteq** [astropy/astropy.github.com#190]
As discussed at the CC meeting in 2017, we are going to "re-brand" the affiliated package/core package ecosystem to have "Astropy Project Packages" in addition to the affiliated.  Should re-write the words about that on the web site.

**Comment by kelle** [comment]
Now we're thinking the two labels will be "Astropy Coordinated" and "Astropy Affiliated" packages.

**Comment by bsipocz** [comment]
oh, pity, I kind of liked the logic in the "Astropy Project packages" and "Astropy Affiliated"

**Comment by astrofrog** [comment]
The issue was that it would be confusing because one could say that affiliated packages were packages of the astropy project but not astropy project packages...

**Comment by eteq** [comment]
A related but not quite the same topic: #201

**Comment by astrofrog** [comment]
Done by @eteq in https://github.com/astropy/astropy.github.com/pull/327!
