### ISSUE TITLE
Simplify role-changing machinery with json and js

### ISSUE THREAD

**Issue by eteq** [astropy/astropy.github.com#194]
Right now it's a bit awkwardly complicated to update the roles - you have to update a special-format ``roles.txt`` file, and then run a script locally and remember to commit both with git.  That works for now, but A better system might be to:

- [ ] change ``roles.txt`` to a ``roles.json`` file
- [ ] use code like what we have in the affiliated package page to populate a table *from* the JSON using a javascript function (which would run locally and is very fast - this has been in practice very stable/easy on the ``affilaited/index.html``).
- [ ] include the roles *descriptions* in the``roles.json`` as well - then do a bit more js tricks to get the roles list to appear on the web site.

Once these are all done, it'll be easy to update the roles in a single commit rather than the awkward 2- or 3- stage process currently required (which also requires knowing to run the script).

Also #167 could be much more easily addressed with this all in place - there could be an additional json field for past holders of the role, and the js could include that at the bottom of the page or something.

**Comment by apooravc** [comment]
@eteq Working on it.
