### ISSUE TITLE
Update logo to focus on the "project"

### ISSUE THREAD

**Issue by eteq** [astropy/astropy.github.com#200]
As discussed in more detail in #193, the recognition of Astropy has improved enough that it's probably no longer necessary for the front page logo to say "A community Python library for Astronomy".  See #193 for a lot more discussion about the exact preferred logo, but it looked to me like this was the sketch of the one settled on:

![image](https://user-images.githubusercontent.com/346587/31261003-b9fe9b6c-aa1f-11e7-8fd2-1e747ca0d54f.png)

This will need to be added to https://github.com/astropy/astropy-logo before we can add it to the web site, but @granttremblay can hopefully do that soon.

**Comment by granttremblay** [comment]
Attached are three updated designs. I've fixed the issue with the end of the snake's tail, and corrected the font to Source Sans (it was previously erroneously set to Open Sans). 

@eteq would you prefer we "vote" / tweak the logo here? I can then make a PR on astropy-logo with the .svg and .png files for the "final" design that we decide upon. 


![3-01](https://user-images.githubusercontent.com/2238418/31398496-24ea1c72-adb7-11e7-804f-3de8e0b4aae8.png)
![2-01](https://user-images.githubusercontent.com/2238418/31398497-24f3f8fa-adb7-11e7-9b45-8a79a9c402ce.png)
![1-01](https://user-images.githubusercontent.com/2238418/31398499-24fe30e0-adb7-11e7-9f5a-5169eb35e446.png)

**Comment by bsipocz** [comment]
I would vote for the middle one.

**Comment by bsipocz** [comment]
ohh, but I don't want to be the decision maker on the new logo...

**Comment by apooravc** [comment]
@bsipocz @granttremblay @eteq If there's still a need for vote, I've created a poll out of those 3 designs above, respectively as "Image 1/2/3", here [Astropy logo poll](http://www.strawpoll.me/15023869)

**Comment by eteq** [comment]
Since there were 3 votes (@kelle gave a 👍 to @bsipocz's comment), I went ahead and merged #218.  So will close this.

(P.S. @apooravc - thanks for setting up the poll - in this case it wasn't necessary, but a good thought.  Just one thing to keep in mind: we try to keep history in the github issues/PRs, so if we *had* used that we'd want a comment at the end noting the results)
