### ISSUE TITLE
Consider whether drop-down docs menu should include affiliated packages

### ISSUE THREAD

**Issue by eteq** [astropy/astropy.github.com#201]
The [Sunpy web site](http://sunpy.org/) has a nice drop-down from the "documentation" menu that shows both the Sunpy package itself and some of the affiliated packages.  By contrast, the [Astropy site](http://www.astropy.org/index.html)'s documentation drop-down lists all the various older versions.

One could argue that it would be more useful to show some of the other packages in our ecosystem rather than older versions of the core package.  I tend towards the idea that the astropy coordinated packages (with the core at the top) would be the list in this drop-down.  But another option might be coordinated *and* affiliated.

The main challenge with either of these is that we would want this to be automated using the affiliated.json file.  Otherwise we'd have to constantly remember to update the site whenever any of the coordinated packages change, which is unrealistic.  So that would be a substantial (but not necessarily *hard* - the code in https://github.com/astropy/astropy.github.com/blob/master/js/functions.js could probably be reused with some changes) modification to the pages.

Thoughts?  We discussed this some at the coordination meeting, but it wasn't clear we came to consensus.

**Comment by bsipocz** [comment]
I would vote for having only the coordinated (and vaguely remember that this was the consensus at the cc meeting, too), and maybe we can have a link at the bottom to the affiliated package page. Otherwise that drop down will be super crowded.

**Comment by pllim** [comment]
I don't think this is relevant anymore with pyOpenSci partnership. Even with legacy ones, there are almost 50 now, the dropdown would be horrible.
