### ISSUE TITLE
Introduce optional entries to the affiliate package registry

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy.github.com#203]
Would it be possible to introduce entries in the affiliate package registry for the appveyor and RTD username? We use the registry file to populate the dashboard, and currently it's inaccurate at quite a few points as we try to populate it using incomplete data.

http://www.astropy.org/astropy-dashboard/status.html

**Comment by astrofrog** [comment]
I don't have any objections to this as it shouldn't increase the JSON size much.
