### ISSUE TITLE
"Becoming an Affiliated Package" suggests Python 3 is still optional

### ISSUE THREAD

**Issue by DFEvans** [astropy/astropy.github.com#233]
The instructions on "[Becoming an Affiliated Package](http://www.astropy.org/affiliated/)" talk about Python 3 compatibility being "encouraged", and that compatibility via the _six_ package is recommended. However, both of these statements are in disagreement with the linked [Coding Guidelines](http://docs.astropy.org/en/stable/development/codeguide.html#writing-portable-code-for-python-2-and-3) - Python 3 is mandatory, and _six_, etc., is not permitted.

**Comment by granttremblay** [comment]
Thanks for the heads up, @DFEvans! I'll fix this with an upcoming PR.

**Comment by granttremblay** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Python 3 Requirement Language https://github.com/astropy/astropy.github.com/issues/233](https://trello.com/c/uInmf93q/4-fix-python-3-requirement-language-https-githubcom-astropy-astropygithubcom-issues-233)
