### ISSUE TITLE
A rotating set of new, pretty backdrops for the landing page

### ISSUE THREAD

**Issue by granttremblay** [astropy/astropy.github.com#242]
The main landing page for the website looks great, but hasn't changed much in the past few years. 

I propose implementing a (limited and curated) set of new backdrops against which the main Astropy logo is set. 

We could potentially choose several new backdrops that could rotate (e.g., with each page load, or perhaps on a time cycle - say, every day or so). 

A very quick example, which uses the gorgeous new HST 28th anniversary image, is attached. We could select 5-10 backdrops that could highlight e.g. extragalactic stuff, or even simulations - we need not only show nebulae!  

<img width="1850" alt="screen shot 2018-05-07 at 5 46 38 pm" src="https://user-images.githubusercontent.com/2238418/39726937-bbc620f8-521e-11e8-9c57-04531f13226b.png">

**Comment by granttremblay** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New Pretty Rotating Backdrops](https://trello.com/c/TXIo7Ddg/3-new-pretty-rotating-backdrops)

**Comment by pllim** [comment]
Will this drain data plan on mobile devices? Something to consider.

**Comment by granttremblay** [comment]
Good point! We could have a lightweight fallback image for all loads to a mobile OS.

**Comment by pllim** [comment]
Don't see any PR linked to this and it has been 6 years.
