### ISSUE TITLE
Vertical spacing in team page

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy.github.com#250]
It looks like there is now too much vertical spacing in the team page:

http://www.astropy.org/team.html

<img width="1059" alt="screen shot 2018-06-20 at 10 32 32" src="https://user-images.githubusercontent.com/314716/41650146-4417de38-7475-11e8-83d7-8a73f3be7415.png">

Is this a result of the changes to the affiliated package page?

**Comment by granttremblay** [comment]
Ooof, yes! I'm sorry! this is my fault - the team table will require a unique selector so as not to inherit the spacing of the affiliated table. Will try to fix this today and issue a PR.
