### ISSUE TITLE
Enable HTTPS for Astropy site?

### ISSUE THREAD

**Issue by adrn** [astropy/astropy.github.com#264]
Now that GitHub pages [supports SSL/HTTPS for custom domains](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/), we should consider using HTTPS for the main Astropy site.

**Comment by eteq** [comment]
In principal this is a great idea.  The one question I have is whether that's hard to do given our DNS provider.  Will look into this.

**Comment by eteq** [comment]
Ok, I think I've got this working.  You'll see that "astropy.org" now redirects straight to "https://www.astropy.org".  So I think this is all done.
