### ISSUE TITLE
Remove the footnote stuff for roles

### ISSUE THREAD

**Issue by eteq** [astropy/astropy.github.com#283]
As discussed at the coordination meeting 2018, we don't think the footnotes that say "Would prefer deputy role" should be removed. @astrofrog I believe wants to downgrade all of his leads with that footnote to deputy on that. I should probably do that.

**Comment by pllim** [comment]
Is this the same as "change blue names to unfilled" as discussed at the meeting? I thought @adrn had a PR to do that but maybe I misunderstood.

**Comment by bsipocz** [comment]
> Is this the same as "change blue names to unfilled" 

As I understand it is.

**Comment by adrn** [comment]
I think this is different, but related, and not clear without the context of in-person discussions at the meeting 😄. As far as I understand, this issue also pertains to removing the bit of javascript / code that checks for a leading 1 and automatically turns names blue / adds the superscript. But @eteq can correct me if I'm misremembering!

**Comment by pllim** [comment]
I am all for removing Javascripts.

**Comment by astrofrog** [comment]
This was done a little while back
