### ISSUE TITLE
Remove "Other astronomy packages" section?

### ISSUE THREAD

**Issue by olebole** [astropy/astropy.github.com#304]
The affiliated packages page has a section "Other astronomy packages" that seems quite outdated nowadays. The kapteyn package is f.e. only for Python 2.6. These packages can't serve as recommendation anymore, at best they mislead visitors of the page.
IMO this section should be just removed.

**Comment by bsipocz** [comment]
Do you have time to open a PR for this?

**Comment by olebole** [comment]
Sure, I just wanted to see if it is opportune.
