### ISSUE TITLE
add links to various Project dashboards

### ISSUE THREAD

**Issue by kelle** [astropy/astropy.github.com#307]
I have just learned about two dashboards (made by @bsipocz and @sosey) which provide useful info about the status of the entire Project, including affiliated projects. These should be linked to somewhere, probably on both the About page and the Contribute page.
- http://www.astropy.org/astropy-dashboard/status.html
- http://www.stsci.edu/~sosey/affiliated_summary.html

**Comment by bsipocz** [comment]
@astrofrog made it, I'm just a user here :)

**Comment by pllim** [comment]
Both dashboards died.

**Comment by astrofrog** [comment]
We need a status dashboard for status dashboards
