### ISSUE TITLE
Is userecho used?

### ISSUE THREAD

**Issue by smoh** [astropy/astropy.github.com#308]
> Feature requests from the community are welcome and encouraged. These should ideally be posted to our UserEcho Forum.

in http://www.astropy.org/contribute.html.

It looks like the activity there has been pretty sparse for a while and perhaps the documentation needs to be updated. I hope this is the right place to raise this issue instead of astropy main.

**Comment by bsipocz** [comment]
This is the right place indeed.

@pllim - what was the decision for userecho  during the coordination meeting? As I recall we said it should go as a dead end try, but I'm not 100% sure I remember right or just wishfully think.

**Comment by pllim** [comment]
@bsipocz , here is the relevant summary from Coordination Meeting last year -- https://github.com/astropy/astropy/wiki/Minutes-for-Astropy-Meeting-2018#tuesday-dec-4-2018

**Comment by bsipocz** [comment]
That reads to me that it's preferable indeed to remove the links to userecho from the docs linked above. 

PR is welcome.

**Comment by pllim** [comment]
I vaguely remember @astrofrog saying that he prefers to have a replacement in place first?

**Comment by bsipocz** [comment]
It's not in the docs though ;) PRs for the replacement is welcome, too, but the current state is a bit confusing. Maybe we could just remove the link but not yet delete userecho?

**Comment by eteq** [comment]
I agree with https://github.com/astropy/astropy.github.com/issues/308#issuecomment-472144528 here - remove the link since we don't really actively want to advertise it, but don't delete the content.

**Comment by smoh** [comment]
Should the users direct feature requests to the astropy github repository? I'm happy to fix this (link) if I know how it should be changed.

> Feature requests from the community are welcome and encouraged. These should ideally be posted to our [astropy github repository](https://github.com/astropy/astropy).

**Comment by bsipocz** [comment]
@smoh - no, we don't have a replacement for it, so just please remove the link. (The original vision was to have userecho for the long term feature wishes that may arch over several packages, e.g. "we need spectroscopy". this at the end proved to be neither very helpful nor picked up by the user community).
