### ISSUE TITLE
Fix https://astropy.org access to work like https://www.astropy.org 

### ISSUE THREAD

**Issue by eteq** [astropy/astropy.github.com#320]
This is a follow-on to #264 (and partly prompted by astropy/pytest-astropy#18): while https://www.astropy.org works correctly, as does http://astropy.org,  https://astropy.org still gives a "not secure" problem that suggests the SSL certificates haven't been updated.

I *believe* I've updated everything following these GitHub guides:
* https://help.github.com/en/articles/securing-your-github-pages-site-with-https
* https://help.github.com/en/articles/setting-up-an-apex-domain

But it doesn't seem to work.  If I get time later I might investigate, but if anyone has any ideas I'm all ears... (cc perhaps @adrn @saimn ?)

**Comment by saimn** [comment]
The redirection to https://www.astropy.org/ seems to be working now:
```
❯ curl -I https://astropy.org/
HTTP/2 301 
server: GitHub.com
content-type: text/html
location: https://www.astropy.org/
```

**Comment by eteq** [comment]
Aha, so it is!  The internet apparently just needs a bit more time...
