### ISSUE TITLE
Re-arrange roles JSON to be more readable

### ISSUE THREAD

**Issue by eteq** [astropy/astropy.github.com#326]
As brought up in https://github.com/astropy/astropy.github.com/pull/325#issuecomment-499260458 (and me internally every time I have to edit that section...), the roles.json file is very awkward to use for the sections with a lot of "sub-roles".  It would be better if instead of the form being:
```
...
"sub-role" : ["1", "2", "3"],
"lead" : ["a", "b", "c"],
"deputy" : ["d", "e", "f"],
...
```

instead it was something like 
```
...
"sub-role" : [{"name": "1", "lead": ["a"], deputy: ["d"] },
                     {"name": "2", "lead": ["b"], deputy: ["e"] },
                     {"name": "3", "lead": ["c"], deputy: ["f"] }]
...
```
that would make updating the list a lot easier to read.  But would require changes to the page javascript...

**Comment by pllim** [comment]
I was just about to open an issue about this, and I am glad there is already one. :100:
