### ISSUE TITLE
Revamp install instructions to be more dynamic

### ISSUE THREAD

**Issue by eteq** [astropy/astropy.github.com#333]
I've seen several examples of this now, but the best one is probably this one: https://pytorch.org/ (screenshot at the bottom).  The idea is that there's a whole bunch of install instructions that get generated for various versions, platforms, etc.

![image](https://user-images.githubusercontent.com/346587/60924112-fe19a180-a265-11e9-95df-a98e8f775900.png)

I wonder if there might be a generic implementation of this, but a few minutes searching doesn't reveal anything obvious to look for on the pytorch page...

**Comment by pllim** [comment]
No.
