### ISSUE TITLE
JS fix needed: multiple e-mail addressed in affiliated package register

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy.github.com#345]
Currently it's not possible to specify multiple e-mail addresses for maintainers for an affiliated package resulting some only list the e-mail of only one of the maintainers. In other cases even when multiple addresses are listed, only the last one is being picked up.

**Comment by pllim** [comment]
No longer relevant. Listing will be from pyOpenSci going forward. Existing listing will be frozen.
