### ISSUE TITLE
Archive the old website repo

### ISSUE THREAD

**Issue by zdroid** [astropy/astropy.github.com#362]
This one: https://github.com/astropy/old-astropy-website-src

To prevent possible necro-ing. Issues are not allowed, but that doesn't solve all possible mishappenings. I am unaware if there are other unofficially archived repositories, but they should be archived from settings aswell.

**Comment by astrofrog** [comment]
I wonder if we should just push that repo to a branch here then delete the old repo

**Comment by zdroid** [comment]
That's also a good idea, but it may require changing many legacy links (like in this repo's readme).

**Comment by zdroid** [comment]
Any news on this? I've seen some other repos on this organization archived.
