### ISSUE TITLE
Add pyregion to affiliated package list

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy.github.com#41]

**Comment by sudheesh001** [comment]
@astrofrog Could you provide more information regarding this ? Is it this [link](https://pypi.python.org/pypi/pyregion) ?

**Comment by astrofrog** [comment]
@sudheesh001 - yes, and the repository is here: https://github.com/astropy/pyregion

**Comment by sudheesh001** [comment]
Does this also fall under the category of
```
stable: yes
provisional: yes
```

**Comment by astrofrog** [comment]
@sudheesh001 yes, thanks!

**Comment by sudheesh001** [comment]
Same here @astrofrog Good to close. :+1:

**Comment by astrofrog** [comment]
Thanks!
