### ISSUE TITLE
Remove inactive maintainers from coordinated packages

### ISSUE THREAD

**Issue by pllim** [astropy/astropy.github.com#410]
I don't think the following people are actively maintaining anymore (ordered by last name):

* Steve Crawford
* Nick Earl
* Michael Seifert

xref astropy/astropy-project#162

**Comment by MSeifert04** [comment]
I can confirm that I'm too inactive currently to fulfill my roles.

I've mailed at coordinators@astropy.org on June 10th about my resignation from the roles in astropy (and in a separate mail to matt and steve about resignation from ccdproc) but totally forgot to follow-up on the mail.

So I'm totally okay with being removed from the maintainer/deputy roles.
