### ISSUE TITLE
remove unnecessary escaping from regex _email_regex_str

### ISSUE THREAD

**Issue by sudheesh001** [astropy/astropy.github.com#45]
Currently the regex given by
`[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}` throws a warning for `Bad or unnecessary escaping`. I think this should be corrected to `[A-Z0-9._%+-]+@[A-Z0-9.-]+[.]{1}[A-Z]{2,4}` so that the hint stops throwing this warning. Both the regex essentially convey the same meaning.

Is this a good thing to change ?

**Comment by eteq** [comment]
@sudheesh001 - can you be a bit more specific where this regex appears?

**Comment by sudheesh001** [comment]
It looks like this doesn't occur anymore. It was showing up on the error messages in the console when you open the website. Closing this.
