### ISSUE TITLE
Status and Python 3 - compliance of omnifit package

### ISSUE THREAD

**Issue by dhomeier** [astropy/astropy.github.com#459]
@hamogu noted earlier today that https://github.com/RiceMunk/omnifit appears to be the only affiliated package that has not been updated to Python 3 at this point. While the last release indeed dates more than 6 years back, development on GitHub has been ongoing, albeit slow.
In fact I was able to pip-install it from git+https://github.com/RiceMunk/omnifit.git under python3.9 without any issues, passing all but 3 tests (units-related). So the package appears in good-enough shape to keep its affiliated status. Should we

- [ ] Update its py3 label, although there is no official 3.x variant on PyPI?
- [ ] Ping maintainers to at least get a pip-installable py3 version of the current release up?
- [ ] Encourage them to look into the issues with the current `units`?

**Comment by hamogu** [comment]
It seems that the last code merge was in 2019 - ans that was an automated upgrade from the astropy-template. Maybe reach out to the maintainers and see if they plan to maintain it?

**Comment by dhomeier** [comment]
Yes, I missed that those were from automated requests – the last actual code maintenance indeed seems to have been in 2015. Does not mean it is no longer of use though.

**Comment by dhomeier** [comment]
Discussion in omnifit/issues#38 shows there definitely are maintenance efforts going on. :)

**Comment by pllim** [comment]
Looks like @dhomeier has advised the maintainer at RiceMunk/omnifit#43 . While I understand the maintainer isn't paid and all, we also cannot let rotting packages stay as Affiliated. Is it fair for me to propose adding to the formal policy that if we have started re-reviewing but glaring problem is not fixed in, say, 6 months, we remove the Affiliated status and they have to re-apply?

**Comment by hamogu** [comment]
Whatever the current affiliated editors (i.e. @pllim and @dhomeier) deem reasonable is reasonable to me. On https://www.astropy.org/affiliated/ is already says "Use Python 3.x. Packages are allowed to be 2.x compatible, but must support recent versions of Python 3.x." and "Note however that if packages become unmaintained or do not meet the standards anymore, they may be removed from the list of affiliated packages." so in principle you could decide to remove that package right now. I don't think that's a nice way of doing business, but "please fix in the next 6 months" is totally reasonable and absolutely within the discretion of the current editors under the current policies.

**Comment by dhomeier** [comment]
Agreeing on all of the above, in particular the bit about the time frame – especially as the mandatory 3.x support was not in effect the last time that package was updated. Also, Python 3 is no longer in fact an issue here (apart from the lack of a corresponding PyPI entry); the only problems at least as far as covered by the tests are related to the evolving unit support in Astropy+Numpy. And that's something that could perhaps even go unnoticed in other packages for quite some time.

**Comment by pllim** [comment]
@dhomeier , do you want to tell the author about the 6-month grace period, perhaps starting 2022-01-01, and we will decide on 2022-07-01?

**Comment by dhomeier** [comment]
The actual code fixes should be a breeze; I have zero experience with preparing stuff for PyPI, so cannot comment on that, but I guess most work will be getting a working test setup again, as it's still all based on Travis.

**Comment by dhomeier** [comment]
Yes, I was mainly getting at whether there are any updated docs in the package template or such, which could be of help.

**Comment by pllim** [comment]
Package template has template for CI via Actions but not Travis: https://github.com/astropy/package-template/tree/cookiecutter/%7B%7B%20cookiecutter.package_name%20%7D%7D/.github/workflows

As for PyPI, the project uses [publish.yml](https://github.com/astropy/pytest-doctestplus/blob/main/.github/workflows/publish.yml) but we do not impose it on affiliated packages, because the actual commands to build the dist can be very code specific.
