### ISSUE TITLE
Simplify install instructions?

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy.github.com#47]
I think the MacOS X instructions on the home page (http://www.astropy.org/) should be updated:
- MacPorts is now no longer a good option compared to Anaconda, so it should definitely not be mentioned first. I think we can always put a sentence along the lines of 'Other options include MacPorts, Fink, etc.'
- I think Fink should also be a secondary option
- I personally think Anaconda and Ureka should be the first suggested solutions and emphasize the ease of installation.
- This page is scary: http://docs.astropy.org/en/stable/install.html and should maybe include a note at the top that these are detailed instructions, but for most people what is at http://www.astropy.org/ is fine?

Any other ways we can simplify the install instructions?

**Comment by embray** [comment]
Apropos nothing to do with Astropy, I was on the website for [certbot](https://certbot.eff.org/) and right on their front page they have a really slick example of this that we could borrow from--somehow I immediately thought of this issue.

Something similar for Astropy would be great.  It doesn't even have to be quite as detailed (that is, in most cases I don't think Astropy needs instructions for lots of different Linux distros).  But something like "Select your OS" and then for each OS a drop down list of different install methods, perhaps with hints for who that particular method is most appropriate for.

**Comment by astrofrog** [comment]
@embray - yes, that would be great!

**Comment by hamogu** [comment]
@astrofrog : This idea is so great, that somebody already implemented it: At www.astropy.org ;-)

**Comment by astrofrog** [comment]
@hamogu the main issue is that the instructions on the main page are still too vague and some things need to be re-ordered. For instance, I don't think we should even mention fink anymore. For people who do use say MacPorts, it's not clear enough what they should do - hence my suggestion that once you've selected your operating system you should also pick your installation method and end up with actual instructions (e.g. sudo port install py36-astropy).

**Comment by hamogu** [comment]
We might then need instruction on how to find out how astropy was installed, too, specifically since many users have multiple python installations (system + anadonda + CIAO in my case) and potentially astropy is installed in more than one of them and users might not really track which versions they really use...

**Comment by embray** [comment]
@hamogu Again, see astropy/astropy#1807 :)

**Comment by astrofrog** [comment]
The instructions at astropy.org are now pretty simple, so I'll go ahead and close this :)
