### ISSUE TITLE
Add links to GitHub profiles of team members

### ISSUE THREAD

**Issue by mwcraig** [astropy/astropy.github.com#498]
Other projects, like [numpy](https://numpy.org/teams/) and [scipy](https://scipy.org/teams/) do this.  

It would make sense to me to start with lifetime contributors and proceed from there.

**Comment by weaverba137** [comment]
Duplicate of #323?

**Comment by weaverba137** [comment]
@mwcraig, I don't actually have permission to close this as duplicate.  Maybe you can? Or @pllim or @eteq?

I read through #323 carefully and this really is a duplicate.

**Comment by mwcraig** [comment]
Thanks, closing...

**Comment by hamogu** [comment]
Duplicate, see above.
