### ISSUE TITLE
Bug in contribute page header

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy.github.com#61]
There's a bug in the contribute page header: the "astropy" text on the left that links to the main page is duplicated.

http://www.astropy.org/contribute.html

![screen shot 2015-04-22 at 12 33 56](https://cloud.githubusercontent.com/assets/852409/7272565/1bf47104-e8ec-11e4-9b62-c64fa92d5c1e.png)

**Comment by embray** [comment]
Same issue on this page: http://www.astropy.org/help.html  But not on About or Affiliated Packages.

**Comment by embray** [comment]
Should be fixed by #68.  Thanks @cdeil !

**Comment by cdeil** [comment]
@embray - Thanks for fixing this!
