### ISSUE TITLE
Search on main page results in warning because of use of http

### ISSUE THREAD

**Issue by braingram** [astropy/astropy.github.com#610]
I'm using firefox on a mac m1, when I visit:
https://www.astropy.org/
and use the search box I am presented with a warning:
<img width="364" alt="Screenshot 2024-07-16 at 4 45 20 PM" src="https://github.com/user-attachments/assets/fc350486-3a9d-4cc2-88c8-4de2701f429e">
due to the use of `http` instead of `https` in the search.
https://github.com/astropy/astropy.github.com/blob/745c64e0a6dabd11a5b73de1ad0c083a9585ab33/index.html#L94

**Comment by pllim** [comment]
Yes, I think we can switch to HTTPS. Are you interested to submit a PR? Thanks!

**Comment by braingram** [comment]
Thanks. No, I'm not at all familiar with this repository.

**Comment by pllim** [comment]
Let me double check with @eteq though. I vaguely remember some discussion on why it is still HTTP but I don't remember where we talked about it.

**Comment by pllim** [comment]
Maybe it was this comment but maybe the comment is only for dev docs and not stable docs? 🤷‍♀️ 

https://github.com/astropy/astropy.github.com/pull/591#issuecomment-2121188535

**Comment by pllim** [comment]
Turns out it was everywhere. See https://github.com/astropy/astropy.github.com/pull/623
