### ISSUE TITLE
Page on Governance?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy.github.com#618]
I cannot seem to find a page about Astropy Governance on the website. Do we not have one or it is hidden under another page somewhere?

**Comment by hamogu** [comment]
It's not the website. It's exposed as https://github.com/astropy/astropy-project with policies, procedures, reports by finance etc.
We *could* render a selection of those documents to make them part of the homepage, but that seems like more effort than it's worth - the beauty of having it in a repro is that it can be updated by PR, GH renders md files for us at no effort, and we don't have to keep a second place in sync (e.g. if travel-policy.md gets split into flight-policy.md and hotel-policy.md - I'm not saying that that's going to happen, but just giving an example where links could easily get out of sync). What we could have is a link to the repro to make it easier to fine for people (the expectation to find something in the website is reasonable).
