### ISSUE TITLE
Add link to tutorials page

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy.github.com#62]
Currently there's no link to the Astropy tutorials page (http://www.astropy.org/astropy-tutorials/) from the web page (http://www.astropy.org/), so it's hard to find.

I guess it should be added in the header, but maybe then there's too many items for mobile devices?

cc @adrn @astrofrog

**Comment by embray** [comment]
:+1: @astrofrog ? @eteq ?  Any reason not to merge this?

**Comment by embray** [comment]
IIRC on mobile view the header will collapse down to a dropdown menu so not a problem.

**Comment by embray** [comment]
Confirmed, adding this just adds another menu item in low width mode, so it looks great IMO.

**Comment by embray** [comment]
(When I say this I mean I just tried it locally; didn't realize at first this wasn't already a PR but I can make it one)

**Comment by astrofrog** [comment]
:+1: from me in principle once there is a PR :)

**Comment by embray** [comment]
Perhaps you've already seen, but there's a related issue at astropy/astropy#3661

**Comment by cdeil** [comment]
If I understood correctly the tutorials will be removed in favour of the example gallery?
Closing this issue.

(If some action is needed, please open a new action describing what to do.)
