### ISSUE TITLE
Remove Twitter?

### ISSUE THREAD

**Issue by kelle** [astropy/astropy.github.com#632]
@mwcraig : should we remove the role or change to X.  or just mark as unfilled?

**Comment by mwcraig** [comment]
I would be inclined to remove the role but make sure to keep the account so that no one else can take the name. I'd also stop linking to it. No need to make a big deal out of it, just let it fade away....

**Comment by pllim** [comment]
Please see https://github.com/astropy/astropy.github.com/pull/634
