### ISSUE TITLE
Add new code of conduct to website

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy.github.com#65]
Once it has been finalized, we should add the new code of conduct to the Astropy website! :)

cc @kelle @AlexaVillaume @eteq @astronomeralex

**Comment by wkerzendorf** [comment]
I thought it should be finalized and send to `astropy-dev` first? I don't really care, but I thought that's what was discussed.

**Comment by astrofrog** [comment]
Indeed! This is just a reminder that we should eventually add it to the website once it has been approved :)

**Comment by AlexaVillaume** [comment]
I made the changes that I wanted to make to it. I think all the additional thoughts at the end have been addressed too. Are we waiting on anything before calling it finished?

**Comment by eteq** [comment]
Was just going through and noticed this - it was added in #75, so I'm closing this
