### ISSUE TITLE
https://www.astropy.org/affiliated/ does not work correctly

### ISSUE THREAD

**Issue by olebole** [astropy/astropy.github.com#74]
Hi,

the SSL-enabled web page https://www.astropy.org/affiliated/ does not show the package registry. The table stays in the state "Loading...".

**Comment by embray** [comment]
It's working for me, but only if I go to http, not https.  The latter gives me certificate errors (ssl_error_bad_cert_domain) which seems to be related to the site being hosted on GitHub and using one of GH's certificates.

**Comment by eteq** [comment]
I'm seeing the same as @embray.  @olebole, did you see a link to the https version somewhere?  I didn't even realize that existed (as @embray said, it's all hosted behind the scenes by github).

**Comment by olebole** [comment]
All on Firefox (Ubuntu) and Iceweasel (Debian):

With http, all is OK. When I load it with https, I first also get a certificate warning. When I then allow the page to display, the table stays as hown in the image:
![affiliated-https](https://cloud.githubusercontent.com/assets/397223/8147759/093223c2-127c-11e5-8c9b-f55577846eb3.png)

The error console then shows (sorry for German; should be understandable however):
```
10:01:06.632 Laden von gemischten aktiven Inhalten "http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,700" wurde blockiert.1 affiliated
10:01:06.636 Laden von gemischten aktiven Inhalten "http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" wurde blockiert.1 affiliated
```
Both with a link to [this webpage](https://developer.mozilla.org/en-US/docs/Security/MixedContent). So, it may depend on the web browser settings (I didn't touch them however), but it seems that the https page should load everything via https.

Would it be a problem to switch all links to https?

**Comment by embray** [comment]
Ah, it looks like it's defaulting to blocking non-secure external resources when accessing the site via HTTPS.

**Comment by embray** [comment]
I believe full HTTPS support on GitHub pages hosted sites is still an open issue.  See isaacs/github#156.

So I think the only practical solution would be to switch to a different hosting provider.  However, there's also nothing on astropy.org that I think necessitates HTTPS.  I'm not really a strong believer in HTTPS-all-the-things when it comes to sites that users don't send any data to.

**Comment by olebole** [comment]
I'd agree in this. However, there are people who just use https (and don't change the default in their browser), and they will run into this error.

**Comment by embray** [comment]
Too bad for them I guess?  I would tend to think people making such settings are going to be aware of the potential drawbacks, and look to it when something doesn't work.  For example I have my browser set to reject *all* cookies by default, so I'm generally aware that when something on a site isn't working I probably have to look at what cookies it's trying to set.

**Comment by olebole** [comment]
Maybe switch off https completely until it works? If parts are non-secure, it is useless anyway.

**Comment by embray** [comment]
That's not something we have any control over.

**Comment by mdboom** [comment]
Using `//` rather than `http://` at the front of the URLs that fail to load should be enough to fix this (since the Google CDNs support `https`).

**Comment by mdboom** [comment]
(I'd like to assign myself here, since I'm working on it, but I'm not part of this org, I guess?  @eteq)

**Comment by eteq** [comment]
@mdboom - added you to the org and assigned you

**Comment by eteq** [comment]
Also :+1: to the @mdboom's suggestion if it turns out that makes it work.

Another thing I just noted: https://astropy.github.io/affiliated *does* appear to work... Presumably that means the problem is more in the forwarding of the astropy.org domain then?
