### ISSUE TITLE
Make it easy to get links to sections

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy.github.com#77]
It would be nice to be able to click on section titles or on a ¶ symbol next to them (like GitHub markdown) to get a link to a section.

**Comment by apooravc** [comment]
@astrofrog If it's still needed, should I start adding those permalinks to a single page only or to every page at once?

**Comment by astrofrog** [comment]
@apooravc - if you'd like to work on this, could you try as an example to add these kinds of paragraph markers to http://www.astropy.org/about.html so we can see what it looks like? (this is the page where I always need it when I want to link to the code of conduct specifically)
