### ISSUE TITLE
Make affiliated package page include descriptions

### ISSUE THREAD

**Issue by eteq** [astropy/astropy.github.com#83]
As discussed in #79, now that there's a "description" section in the registry, we should have this be reflected in the affiliated package pages.

The question is where.  The table seems sensible, except that it already has a lot of content and long text descriptions might make it hard to read.  (Although perhaps shortening some of the content in the tables would help this, as @astrofrog suggested in #79)

An alternative is an automated version of the previous "Other Packages" section.

I'll try to get to this at some point, but if someone else wants to take a stab, feel free.

**Comment by hamogu** [comment]
I recently looked for a affiliated package, but had forgotten the name. So, I looked the the table of affiliated (and provisionally affiliated) packages in the astropy docs. That table contains a lot of info that's relevant to package contributors (code repository, name of main maintainer), but little info for somebody that's looking for a package.

I suggest to add a summary/tagline/a few keywords for each package. In turn, the column "code repository" can go. There is a link to the docs for each package and presumably the docs will explain where to get the code. (I think, the column "maintainer" is also not that important here.)

We can save even more space if we make the package name a link to its docs. So, the table would then be (using examples where I know the package well enough):

name/link - status / pipi - description
APLPy - stable - APLPy- plotting of images in WCS with lables, overlays, etc.
ginga - stable - interactive image viewer similar to ds9
phot-utils - devel - photometric functions and pipeline

**Comment by adrn** [comment]
Yes, please!

**Comment by adrn** [comment]
One alternative idea for redesigning to minimize clutter: default view for a row is just
Name, Short description

Click row to expand to get Stable, Maintainer, Docs link, Webpage, Long description

**Comment by mhvk** [comment]
Just came across the same problem as @hamogu and the same conclusion as @adrn - package name and description; click on it to get details.

**Comment by kelle** [comment]
this also just came up at the Madison Tutorial Sprint -- it's very hard to figure out what the packages do. short descriptions are needed.

**Comment by astrofrog** [comment]
Yep, and actually a lot of the things in the table could be condensed, e.g. repo link could be github/bitbucket logo etc. We could even put each package on two lines/rows. At the moment the wrong kind of information is emphasized.

**Comment by astrofrog** [comment]
By the way, the info *is* there in the JSON file, it's just not used for the HTML table.

**Comment by hamogu** [comment]
We are already using the javascript "datatables" package in astropy itself (when you display a tables in the webbrowser).
I think this would also be an excellent use for that: See the example here:

https://datatables.net/examples/api/row_details.html

We can have all the top level info (package name, status, one line description) in the table and then fold out additional info (maintainer, repro link etc.)

**Comment by astrofrog** [comment]
We now include descriptions and user-useful information in the page: https://www.astropy.org/affiliated/index.html - I'll close this but feel free to open a new issue if you think we could improve it further.
