### ISSUE TITLE
Remove mention of binary installers on PyPI for Windows?

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy.github.com#87]
@embray - since you mentioned on the list that you are no longer providing these, should we update the front page of the website?

**Comment by embray** [comment]
Perhaps so.  But I would like to get wheel builds up for Windows.  So maybe it should be changed to mention wheels instead.  (But not until I've actually done it.)

I'll try uploading those today and see how it works out.

**Comment by pllim** [comment]
Can we close this?
